# Generated by Django 3.2.7 on 2021-09-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmembers', '0005_auto_20210911_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growth',
            old_name='growth',
            new_name='name',
        ),
    ]
