# Generated by Django 3.2.7 on 2021-09-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmembers', '0006_rename_growth_growth_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growth',
            old_name='name',
            new_name='growth',
        ),
        migrations.AlterField(
            model_name='growth',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
